version: 2
updates:
    - package-ecosystem: "npm"
      directory: "/client"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "⬆️"
          include: "scope"

    - package-ecosystem: "npm"
      directory: "/"
      schedule:
          interval: "daily"
      commit-message:
          prefix: "⬆️"
          include: "scope"
